### ISSUE TITLE
hybrid-query rocker version conflict with light-codegen

### ISSUE THREAD

**Issue by BalloonWen** [networknt/light-portal#103]
`<version.rocker>0.22.0</version.rocker>` in hybrid-query pom.xml
`<version.rocker>1.2.1</version.rocker>` in light-codegen pom.xml
will cause a method not found exception.

**Comment by stevehu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hybrid-query rocker version conflict with light-codegen](https://trello.com/c/7u1PSmpr/298-hybrid-query-rocker-version-conflict-with-light-codegen)

**Comment by stevehu** [comment]
https://github.com/networknt/light-portal/pull/105
